schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://api.chatadmin-mod.click/
      headers:
        user-agent: JS GraphQL
        Authorization: Token 06bcdcddee18f8cb88f28600c102764a5d587214
      introspect: false
