package com.i69.applocalization

object LocalStringConstants {
    const val sign_in_app_name = "iSixtyNine"
    const val sign_in_app_description = "Connecting Hearts"

    const val search = "Search"
    const val search_drawer = "SEARCH"
//    const val google_maps_key = "AIzaSyBcRX4ReMFKaydkJ5V1gxkpOuROdKSVHLw"
//    const val google_maps_key = "UVVsNllWTjVRbU5TV0RSU1pVMUdTMkY1Wkd0S05WWXhaM2hyY0U5MVVrOWtTMU5XU0V4Mwo="
    const val language_label = "Language"
    const val select_language = "Select Language"


    const val profile_complete_title = "COMPLETE PROFILE"
    const val profile_edit_title = "EDIT PROFILE"
    const val done = "Done"
    const val name_label = "Name"
    const val name_hint = "Enter name"
    const val gender_label = "Gender"
    const val age_label = "Age"
    const val height_label = "Height"
    const val work_label = "Work"
    const val work_hint = "Enter your work…"
    const val education_label = "Education"
    const val education_hint = "Enter your education…"
    const val family_plans_label = "Family plans"
    const val politic_views_label = "Politic views"
    const val ethnicity_label = "Ethnicity"
    const val religious_beliefs_label = "Religious beliefs"
    const val zodiac_sign_label = "Zodiac sign"
    const val politic_views_cell = "Politic views:"
    const val ethnicity_cell = "Ethnicity:"
    const val religious_beliefs_cell = "Religious beliefs:"
    const val zodiac_sign_cell = "Zodiac sign:"
    const val groups_label = "Groups"
    const val interests_label = "Interests"
    const val interests_for = "Interest for"
    const val music_label = "MUSIC"
    const val music = "Music"
    const val add_music_tags = "Add music tags"
    const val movies_label = "MOVIES"
    const val add_movies_tags = "Add movies tags"
    const val movies = "Movies"
    const val tv_shows_label = "TV SHOWS"
    const val add_tv_tags = "Add TV shows tags"
    const val tv_shows = "TV shows"
    const val tv_show = "TV show"
    const val sport_teams_label = "SPORT TEAMS"
    const val add_sport_teams_tags = "Add sport teams tags"
    const val sport_teams = "Sport teams"
    const val sport_team = "Sport team"
    const val photo = "Photo"
    const val add_photo = "ADD PHOTO"
    const val video = "Video"
    const val file = "File"

//    <!--interests-->
    const val add_custom_tags_error_message = "You should enter something"
    const val add_artist = "ADD ARTIST"
    const val add_artist_hint = "Enter artist that you like"
    const val add_movie = "ADD MOVIE"
    const val add_movie_hint = "Enter movie that you like"
    const val add_tv_show = "ADD TV SHOW"
    const val add_tv_show_hint = "Enter tv show that you like"
    const val add_sport_team = "ADD SPORT TEAM"
    const val add_sport_team_hint = "Enter sport team that you like"

    const val enter_your_gender="Enter your gender…"
    const val enter_your_age="Enter your age…"
    const val enter_your_politic_views="Enter your politic views…"
    const val enter_zodiac_sign="Enter your zodiac sign…"
    const val enter_your_ethnicity="Enter you ethnicity…"
    const val enter_your_religious_beliefs="Enter your religious beliefs…"
    const val enter_your_height="Enter your height…"
    const val enter_your_family_plans="Enter your family plans…"
    const val clear="Clear"
    const val enter_keywords_interests="Enter keywords, interests or hobby"
    const val search_user_by_name="Search by name"
    const val maximum_distance="Maximum distance"
    const val age_range="Age range"
    const val looking_for="Looking for"
    const val miles="miles"
    const val personal_label="Personal"
    const val height_range="Height range"

    const val tags_label="Tags"
    const val search_results="Search results"
    const val search_unlock_feature_title="TOP UP COINS"
    const val search_unlock_feature_description="Buy i69 coins - open new world of connections!"
    const val random="Random"
    const val  popular="Popular"
    const val most_active="Most Active"
    const val no_users_found_message="Unfortunately, we could not find anyone based on your search preferences"
    const val interests="Interests"
    const val send_message="Send message"
    const val my_profile="My profile"
    const val no_new_matches_yet="No new matches yet. \nSearch for people now!"
    const val messages="Messages"
    const val hint_enter_a_message="Enter a message"
    const val block="Block"
    const val report="Report anonymously"
    const val contact_us="CONTACT US"
    const val buy_coins="BUY COINS"
    const val buy_coins_purchase="BUY COINS"
    const val  privacy="Privacy"
    const val privacy_drawer="PRIVACY"
    const val settings="SETTINGS"
    const val menu="Menu"
    const val settings_buy="Buy coins"
    const val settings_logout="Logout"
    const val language="Language"
    const val blocked_accounts="Blocked Accounts"
    const val are_you_sure="Are you sure you want to delete your account?"
    const val yes="Yes"
    const val no="No"
    const val delete_account="Delete Account"
    const val blocked_description="BLOCKED"
    const val unblock="UNBLOCK"
    const val chat_coins="Coins"
    const val coins_left="Coins left"
    const val coin_left="Coin left"

    // First Chat
   const val you_have_new_match = "You have new match request!"
   const val wants_to_connect_with_you = "%s wants to connect with you!"
   const val awesome_you_have_initiated = "Awesome! You have initiated a chat. User will receive notification!"

    // One to One
   const val image = "Image"
   const val new_unread_messages = "New Unread Messages!"
   const val user_message = "%s : %s"


   const val loading = "Loading…"
   const val male = "male"
   const val female = "female"
   const val not_enough_coins = "Not enough coins"
   const val dots= "…"
   const val cancel = "Cancel"
   const val select_payment_method = "Select Payment Method"
   const val congrats_purchase = "Congratulations! You get %d coins!"
   const val search_permission = "Please provide Permission for Search."
   const val report_accepted = "Thank you! i69 has received your report."

   const val upload_image_warning = "For uploading more than %d photos, you have to spend %d coins."
   const val user_not_available = "User is currently not available for chat!"
   const val user_coins = "%d Coins"
   const val user_coin = "%d Coin"
   const val gifts = "Gifts"
   const val real_gifts = "Real Gifts"
   const val virtual_gifts = "Virtual Gifts"
   const val coins = "Coins"
   const val buy_gift = "Buy gift"
   const val years = "YEARS"
   const val cm = "CM"
   const val moments_comment = "Moments Comment"
   const val isixtynine = "ISIXTYNINE"
   const val user_moments = "User Moments"
   const val new_user_moment = "New user moment"
   const val share_a = "Share a"
   const val moment = "Moment"
   const val share = "SHARE"
   const val whats_going_hint = "What is going to share"
   const val drag_n_drop_file = "DRAG AND DROP FILE TO UPLOAD"
   const val select_file_to_upload = "SELECT FILE TO UPLOAD"
   const val posting_a_moment_tip = "Posting will appear on your feed"
   const val swipe_to_open_camera = "Swipe To Open Camera"
   const val you_cant_share_moment = "You can not share a moment without picture."
   const val you_cant_delete_moment = "User can able to delete own moments only."
   const val you_cant_add_empty_msg = "Please add comment text."
   const val _or = "(OR)"
   const val feed = "Feed"
   const val story = "Story"
   const val post_comment = "POST A COMMENT"
   const val typemsg = "Type Message"
   const val itemdelete = "Delete"
   const val itemblock = "Block"
   const val itemdreport = "Report"
   const val notificatins = "Notifications"
   const val no_notification_found = "No Notification found."
   const val profilepic = "PROFILE PHOTOS"
   const val rec_gifts = "Received Gifts"
   const val sent_gifts = "Sent Gifts"

   const val default_notification_channel_id = "i69app"


//    <!--     const val general_channel_title" translatable="false = "i69appchannel "-->


//    <!--
//    This is the name that users will see when interacting with this channel.
//    It should describe the category of notifications that will be sent through this channel
//    -->
//    <!-- [START fcm_default_icon_string] -->
     const val default_notification_channel_name = "i69notify"
     const val default_notification_channel_desc = "i69appnotification"

     const val user_number = "%d"
//    <!-- TODO: Remove or change this placeholder text -->
     const val hello_blank_fragment = "Hello blank fragment"

    /// Login
     const val connecting_dots = "Connecting Hearts"
     const val facebook_login = "Login with Facebook"
     const val twitter_login = "Login with Twitter"
     const val google_login = "Login with Google"
     const val terms_and_conditions = "Terms and Conditions"

//    <!--interested in-->
     const val interested_in = "Interested in"
     const val serious_relationship = "Serious Relationship"
     const val casual_dating = "Casual dating"
     const val new_friends = "NEW FRIENDS"
     const val roommates_2_lines = "ROOM\nMATES"
     const val roommates = "ROOMMATES"
     const val business_contacts = "BUSINESS CONTACTS"
     const val man = "MAN"
     const val woman = "WOMAN"
     const val both = "BOTH"
     const val save = "SAVE"
     const val interested_in_error_message = "Please select what your search results should be interested in"
     const val interested_in_help = "Choose categories which you want to be show in."


//    <!--about-->
     const val about = "About"
     const val about_description = "Describe yourself"
     const val about_next = "Next"
         const val about_error_message = "Please describe yourself a bit"


//    <!--tags-->
     const val tags = "Select tags"
     const val next = "Next"
     const val select_tags_error_message = "Please select at least 3 tags"


//    <!--    Complete Profile-->
//    <!--    Gender-->
//    <string-array name="gender = "
//    <item>Male</item>
//    <item>Female</item>
//    <item>Prefer Not to Say</item>
//    </string-array>


//    <!--welcome-->
    const val welcome_title = "Welcome to"
    const val welcome_hint = "You can use iSixtyNine\nto search for:"
    const val welcome_relationships = "RELATIONSHIP"
    const val welcome_text = "To initiate a conversation - just search for a user and send a message"
    const val welcome_button = "Let\'s Go !!! CLICK HERE TO START"


//    <!--    error text-->
    const val photo_error = "You must add a photo."
    const val max_photo_login_error = "You cannot add more than 3 photos at Login."
    const val name_cannot_be_empty = "Name cannot be empty."
    const val gender_cannot_be_empty = "Gender cannot be empty."
    const val age_cannot_be_empty = "Age cannot be empty."
    const val height_cannot_be_empty = "Height cannot be empty."
    const val sign_in_failed = "Sign In Failed!"
        const val something_went_wrong = "Something went wrong!"
    const val select_option_error = "Please Select at Least One Option."


    const val add_story = "ADD STORY"
    const val received_gift = "Received gift"
    const val send_gift = "Send gift"
    const val earnings = "Earnings"
    const val wallet = "WALLET"

    //New
    const val near_by_user = "Near by user"
    const val has_shared_moment = "has shared a moment"
    const val send_git_to = "SEND GIFT TO"
    const val successfully = "Successfully"
    const val you_bought = "You Bought"






    const val viwe_all_comments = "View all comments"

    const val itemedit = "Edit"
    const val camera = "Camera"
    const val gallery = "Gallery"
    const val select_chat_image = "Select Chat Image"
    const val select_profile_image = "Select Profile Image"
    const val select_moment_pic = "Select Moment Photo"
    const val select_story_pic = "Select Story Photo"
    const val select_section_image = "Select Image Section"
    const val location = "Location"
    const val location_enable_message = "CLICK ON 'OK' TO SHARE YOUR LOCATION"
    const val lorem_33_minutes_ago = "33 minutes ago"
    const val lorem_username = "USERNAME"
    const val viwe_all_likes = "View Likes"
    const val text_user_balance = "User Balance : "
    const val text_upgrade_your_balance = "Upgrade Your Balance"


//    <!--    //in ap and string uses//-->

    const val no_likes_found = "No Likes found."
    const val new_movement_added = "New Movement Added."
    const val zero_likes = "0 Likes"
    const val no_comments_found = "No Comments found."
    const val zero_comments = "0 Comments"
    const val request_private_access = "Request Private Access"
    const val cancel_request = "Cancel Request"
    const val enter_mobile_number = "Enter Mobile Number"
    const val submit = "Submit"
    const val enter_pin = "Enter PIN"
    const val select_boku_operators = "Select Boku Operators"
        const val boku_no_operator_mesg = "Sorry, No operators available for your location"
    const val boku = "Boku"
        const val stripe = "Stripe"
    const val proceed_to_payment = "Proceed to Payment"
    const val text_public = "Public"
    const val text_private = "Private"
    const val text_pay = "Pay"
    const val sender = "SENDER"
    const val gift_name = "GIFT NAME"
    const val like = "Like"
    const val comments = "Comments"
    const val reply = "Reply"
    const val liked_by = "Liked By"
    const val accept = "Accept"
    const val reject = "Reject"
    const val text_view = "View"
    const val coins_gift = "Coins Gift"
    const val admin = "Admin"
    const val near_by_user_name_has_shared_a_moment = "Near by user NAME has shared a moment"
    const val notification_sample_app = "Notification Sample App"
    const val ok = "Ok"
    const val payment_successful = "Payment successful"
    const val buyer_canceled_paypal_transaction = "Buyer canceled the PayPal transaction"
    const val msg_some_error_try_after_some_time = "There is some error. Please try after sometime"
    const val please_enter_mobile_number = "Please enter mobile Number"
    const val please_enter_pin = "Please enter PIN"
    const val please_wait_verifying_the_pin = "Please wait, Verifying the PIN ...."
    const val pin_verification_successful_please_wait = "PIN Verification successful, Please wait"
    const val pin_verification_failed = "PIN Verification failed"
    const val please_wait_sending_the_pin = "Please wait, Sending the PIN ...."
    const val fetching_charging_token_please_wait = "Fetching Charging token, Please wait"
    const val authorisation_exception = "AuthorisationException"
    const val charging_payment_exception = "Charging Payment Exception"
    const val charging_token_exception = "Charging Token Exception"
    const val authorisation = "Authorisation"
    const val you_successfuly_bought_the_coins = "You successfully bought the coins"
    const val pin_verification_exception = "PIN Verification Exception"
    const val exception_get_payment_methods = "Exception getPaymentMethods"
    const val sorry_pin_failed_to_send = "Sorry, PIN failed to send"
    const val charging_payment_please_wait = "Charging Payment, Please wait"
    const val try_again_later = "Try again later!"
    const val blocked = "blocked!"
    const val no_enough_coins = "Not enough coins.."
    const val you_accepted_the_request = "You accepted the request!"
    const val you_reject_the_request = "You rejected the request!"
    const val select_image_file = "SELECT IMAGE/FILE:"
    const val wrong_path = "Wrong path"
    const val file_size = "File Size"
    const val your_video_file_should_be_less_than_11mb = "Your video file should be less than 11mb"
    const val notifications = "notifications"
    const val user_cant_bought_gift_yourseld = "User can\'t bought gift yourself"
    const val somethig_went_wrong_please_try_again = "Something went wrong , Please try again"
    const val rewuest_sent = "Request sent"
    const val request_access_error = "Request access error"
    const val request_cancelled = "Request cancelled"
    const val cancel_request_error = "Cancel Request error"
    const val ago = "ago"
    const val are_you_sure_you_want_to_block = "Are you sure you want to block"
    const val beneficiary_name = "BENEFICIARY NAME"
    const val translation = "Translation"
    const val copy = "Copy"
    const val copy_translated_message = "Copy Translated Message"
    const val delete = "Delete"
    const val translation_failed = "Translation Failed"

    const val text_seen = "Seen"
    const val text_skip = "SKIP"
    const val text_apply = "Apply"

    const val buy_subscription = "Buy Subscription"
    const val subscription = "Subscription"

    const val platnium = "platimum"
    const val silver = "silver"


    const val text_gold = "Gold"
    const val text_platnium = "Platinum"
    const val text_silver = "Silver"
    const val what_s_included = "What\'s Included"
    const val maximise_your_dating_with_all_the_benefits_of_premium_plus_extra_features_included = "Maximise your dating with all the benefits of platinum, plus extra features included"
    const val see_who_likes_you = "See who likes you"
    const val maximise_your_dating_with_all_the_benefits_of_n_premium_plus_extra_features_included = "Maximise your dating with all the benefits of\n platinum, plus extra features included"
    const val benefits = "Benefits:"
    const val recurring_billing_cancel_anytime_subscription_automatically_renews_after_trail_ends = "RECURRING BILLING. CANCEL ANYTIME. SUBSCRIPTION AUTOMATICALLY RENEWS AFTER TRAIL ENDS."
    const val maximise_your_dating_with_all_the_benefits_of_n_gold_plus_extra_features_included = "Maximise your dating with all the benefits of \n gold, plus extra features included"
    const val maximise_your_dating_with_all_the_benefits_of_n_silver_plus_extra_features_included = "Maximise your dating with all the benefits of \n silver, plus extra features included"
    const val compare_silver_plan = "Compare Silver Plan"
    const val compare_gold_plan = "Compare gold Plan"
    const val compare_platinum_plan = "Compare Platinum Plan"
    const val no_active_subscription = "No active subscription"
    const val your_balance = "YOUR BALANCE : "
    const val your_subscription = "YOUR SUBSCRIPTION : "
    const val comment_allowed = "Comment Allowed"
    const val comment_not_allowed = "Comment Not Allowed"

    const val chat = "chat"
    const val subscribe = "Subscribe"

    const val following = "Following : "
    const val following_tab = "Following"
    const val text_package = "Package"

    const val follower = "Follower : "
    const val followers = "Followers"
    const val remove = "Remove"
    const val follow = "Follow"
    const val upgrade = "Upgrade"
    const val connect = "Connect"
    const val connected = "Connected"
    const val visitors = "Visitors"
    const val visited = "Visited"

    const val moments = "Moments."
    const val read_more = "READ MORE"
    const val are_you_sure_you_want_to_exit_I69 = "Are you sure you want to exit I69"

    const val are_you_sure_you_want_to_delete_story = "Are you sure you want to delete this story?"
    const val are_you_sure_you_want_to_delete_moment = "Are you sure you want to delete moment?"

    const val do_you_want_to_leave_this_page = "Do you want to leave this page?"

    const val userbalance = "User Balance"
    const val active_no_subscription = "No Active Subscription"
    const val active_subscription = "Active Subscription"
    const val msg_token_fmt = "FCM registration Token: %s"
    const val gold = "Gold"
    const val date = "Date"
    const val day_count = "Day Count"

//    <!--    const val congratulations = "Congratulations you saved 70%"-->

    const val msg_coin_will_be_deducted_from_his = "Coins %1s will be deducted from your account to unlock full search result. CLICK 'OK' TO CONTINUE"
    const val filter = "Filter"
    const val unlock = "Unlock"
    const val compare_price = "Compare Price"
    const val subscribe_for_unlimited = "Subscribe for unlimited use"
    const val to_view_more_profile = "to view More profile"
    const val unlock_this_funtion = "unlock this funtion for 24 hours with %1s COINS"
    const val unlock_this_function_ = "Unlock this function"
    const val dont_have_enough_coin_upgrade_plan = "you don\'t have enough coins for this action , upgrade your coins balance to continue 'OK'"
    const val buy_now = "Buy Now"
    const val are_you_sure_you_want_to_change_language = "Are you sure you want to change language"
    const val are_you_sure_you_want_to_unfollow_user = "Are you sure you want to unfollow user : "
    const val moment_liked = "Moment Liked"
    const val comment_in_moment = "Comment in moment"
    const val story_liked = "Story liked"
    const val story_commented = "Story Commented"
    const val gift_received = "Gift received"
    const val message_received = "Message received"
    const val congratulations = "Congratulations"
    const val user_followed = "User Followed"
    const val profile_visit = "Profile Visit"
    const val something_went_wrong_please_try_again_later = "Something went wrong! Please try again later!"
    const val left = "Left"
    const val dots_vertical = " : "
    const val recurring_billing_cancel_anytime = "RECURRING BILLING. CANCEL ANYTIME."
    const val subscription_automatically_renews_after_trail_ends = "SUBSCRIPTION AUTOMATICALLY RENEWS AFTER TRAIL ENDS."

    const val silver_package = "Silver Package"
    const val gold_package = "GOLD Package"
    const val platimum_package= "Platimum Package"

    const val paypal = "Paypal"
    const val chat_new = "Chat"
    const val maximize_dating_with_premium = "Maximise your dating with all the benefits of premium, plus extra features included"
    const val more_details_= "More details..."
    const val days_left= "%d Days left"
    const val following_count_follower_count = "Following - %1\$d | Followers - %2\$d"
    const val i_am_gender = "I\'m a %s"
    const val prefer_not_to_say = "Prefer Not to Say"
    const val _with_a_ = "%1\$s with a: \"%2\$s\""
    const val with = "with"
    const val label_buy = "Buy"

}
